contact_links:
  - name: Question/s
    url: https://github.com/KitetsuK/Test1TemplateRepo/discussions/categories/q-a
    about: If you have question/s to ask you can find your answer.
      If you don't ask it !
